/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aljava.view;

import com.aljava.classes.DAO;
import com.aljava.classes.ProductDAO;
import com.aljava.model.entities.Products;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GERSON
 */
public class FormProdutos extends javax.swing.JFrame {

    /**
     * Creates new form FormClient
     */
    public FormProdutos() {
        initComponents();
    }

    public void montaTabela(List<Products> products) {
        DefaultTableModel dados = (DefaultTableModel) tbProdutos.getModel();
        dados.setRowCount(0);
        for (Products product : products) {
            dados.addRow(new Object[]{
                product.getId(),
                product.getCodigoBarras(),
                product.getNome(),
                product.getPreco(),
                product.getEstoque(),});
        }
    }

    public void listaProdutos() {
        DAO<Products> dao = new DAO<>(Products.class);
        List<Products> products = dao.obterTodos(5, 0);
        montaTabela(products);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelGeral = new javax.swing.JTabbedPane();
        panelListaClientes = new javax.swing.JPanel();
        txtCampoBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setBounds(new java.awt.Rectangle(170, 40, 0, 0));
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                listaClientes(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(50, 138, 138));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 156, 155));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produtos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(581, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 120));

        panelGeral.setForeground(new java.awt.Color(50, 138, 138));
        panelGeral.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        panelListaClientes.setBackground(new java.awt.Color(255, 255, 255));

        txtCampoBuscar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCampoBuscar.setForeground(new java.awt.Color(22, 22, 22));
        txtCampoBuscar.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtCampoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCampoBuscarKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(50, 138, 138));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_24px.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscarProduto(evt);
            }
        });

        tbProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbProdutos.setForeground(new java.awt.Color(50, 138, 138));
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código de Barra", "Nome", "Preço", "Qtd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.setAlignmentX(1.0F);
        tbProdutos.setAlignmentY(1.0F);
        tbProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbProdutos.setColumnSelectionAllowed(true);
        tbProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbProdutos.setGridColor(new java.awt.Color(255, 255, 255));
        tbProdutos.setSelectionBackground(new java.awt.Color(50, 138, 138));
        tbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProdutos);
        tbProdutos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(0).setMinWidth(45);
            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbProdutos.getColumnModel().getColumn(0).setMaxWidth(60);
            tbProdutos.getColumnModel().getColumn(1).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbProdutos.getColumnModel().getColumn(1).setMaxWidth(150);
            tbProdutos.getColumnModel().getColumn(2).setMinWidth(150);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(45);
            tbProdutos.getColumnModel().getColumn(2).setMaxWidth(400);
            tbProdutos.getColumnModel().getColumn(3).setMinWidth(100);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbProdutos.getColumnModel().getColumn(3).setMaxWidth(110);
            tbProdutos.getColumnModel().getColumn(4).setMinWidth(70);
            tbProdutos.getColumnModel().getColumn(4).setPreferredWidth(50);
            tbProdutos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(50, 138, 138));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        jButton2.setText("Novo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeFormProduto(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListaClientesLayout = new javax.swing.GroupLayout(panelListaClientes);
        panelListaClientes.setLayout(panelListaClientesLayout);
        panelListaClientesLayout.setHorizontalGroup(
            panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelListaClientesLayout.createSequentialGroup()
                        .addComponent(txtCampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListaClientesLayout.setVerticalGroup(
            panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGeral.addTab("PRODUTOS", panelListaClientes);

        jPanel1.add(panelGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 840, 410));

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Desenvolvido por ALJAVATECH - Todos os direitos resevados - 2021");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listaClientes(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_listaClientes
        // TODO add your handling code here:
    }//GEN-LAST:event_listaClientes

    private void tbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutosMouseClicked
        // TODO add your handling code here:
        panelGeral.setSelectedIndex(0);
        ProductDAO dao = new ProductDAO();
    }//GEN-LAST:event_tbProdutosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listaProdutos();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void changeFormProduto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeFormProduto
        // TODO add your handling code here:
        FormNovoProduto tela = new FormNovoProduto();
        tela.setVisible(true);
    }//GEN-LAST:event_changeFormProduto

    private void buttonBuscarProduto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarProduto
        // TODO add your handling code here:
        ProductDAO dao = new ProductDAO();
        List<Products> products = dao.buscarPorNome(txtCampoBuscar.getText());
        montaTabela(products);

    }//GEN-LAST:event_buttonBuscarProduto

    private void txtCampoBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoBuscarKeyPressed
        // TODO add your handling code here:
        ProductDAO dao = new ProductDAO();
        List<Products> products = dao.buscarPorNome(txtCampoBuscar.getText());
        montaTabela(products);
    }//GEN-LAST:event_txtCampoBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane panelGeral;
    private javax.swing.JPanel panelListaClientes;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtCampoBuscar;
    // End of variables declaration//GEN-END:variables

}
