/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aljava.view;

import com.aljava.classes.DAO;
import com.aljava.classes.SalesDAO;
import com.aljava.model.entities.Products;
import com.aljava.model.entities.Sales;
import com.aljava.model.entities.Utilitarios;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEFIN
 */
public class FormVendas extends javax.swing.JFrame {

    private JTextField searchField;
    double totalVenda, preco, subTotal;
    int qtd;

    private Date dataAtual() {
        LocalDate dataAtual = LocalDate.now();
        DateTimeFormatter formatoAmericano = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        SimpleDateFormat dataAmericano = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date dataAtualMySQL = dataAmericano.parse(dataAtual.format(formatoAmericano));
            return dataAtualMySQL;
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }

    private double totalVendaDouble(String valorTotalVenda) {
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
        double valorTotal = 0;
        try {
            valorTotal = numberFormat.parse(valorTotalVenda).doubleValue();
            return valorTotal;
        } catch (ParseException ex) {
            Logger.getLogger(FormNovoProduto.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
    }

    public void buscarProduto() {
        String termo = txtParametroBusca.getText();
        DAO<Products> dao = new DAO<>(Products.class);
        List<Products> products = dao.buscarPorParams(termo);
        for (Products product : products) {
            txtCodigoBarra.setText(product.getCodigoBarras());
            txtNomeProduto.setText(product.getNome());
            txtPrecoUnitario.setText(String.valueOf(product.getPreco()));
            jSpinnerQuantidade.setValue(1);
        }
        txtParametroBusca.setText(null);
    }

    public void montaTabela() {
        DefaultTableModel dados = (DefaultTableModel) tbItensVenda.getModel();

        double subTot = (Double.parseDouble(txtPrecoUnitario.getText()) * Integer.parseInt(jSpinnerQuantidade.getValue().toString()));
        totalVenda += subTot;
        dados.addRow(new Object[]{
            txtCodigoBarra.getText(),
            txtNomeProduto.getText(),
            jSpinnerQuantidade.getValue(),
            txtPrecoUnitario.getText(),
            subTot,});

        txtTotalVenda.setText(String.valueOf(totalVenda).replace(",", "").replace(".", ","));

    }

    /**
     * Creates new form FormVendas
     */
    public FormVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeralVenda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtTotalVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelAddItemVenda = new javax.swing.JPanel();
        txtNomeProduto = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        txtPrecoUnitario = new javax.swing.JTextField();
        txtParametroBusca = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonFinalizarVenda = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        jSpinnerQuantidade = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItensVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");

        panelGeralVenda.setBackground(new java.awt.Color(255, 255, 255));
        panelGeralVenda.setForeground(new java.awt.Color(50, 138, 138));
        panelGeralVenda.setAutoscrolls(true);
        panelGeralVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panelGeralVenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 156, 155));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PDV - VENDAS");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(464, 464, 464))
        );

        panelGeralVenda.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 120));

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Desenvolvido por ALJAVATECH - Todos os direitos resevados - 2021");
        panelGeralVenda.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 730, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("GERSON CORREIA LIMA NETO - CPF 936.956.832-87");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelGeralVenda.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 450, 50));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        txtTotalVenda.setEditable(false);
        txtTotalVenda.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalVenda.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtTotalVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalVenda.setText("0,00");
        txtTotalVenda.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TOTAL: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGeralVenda.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 590, -1));

        panelAddItemVenda.setBackground(new java.awt.Color(255, 255, 255));

        txtNomeProduto.setEditable(false);
        txtNomeProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomeProduto.setForeground(new java.awt.Color(51, 51, 51));
        txtNomeProduto.setToolTipText("Código de barras ou Nome do produto");
        txtNomeProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        txtNomeProduto.setMinimumSize(new java.awt.Dimension(11, 38));
        txtNomeProduto.setPreferredSize(new java.awt.Dimension(11, 38));

        txtCodigoBarra.setEditable(false);
        txtCodigoBarra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigoBarra.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigoBarra.setToolTipText("Código de barras ou Nome do produto");
        txtCodigoBarra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código Barras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtPrecoUnitario.setEditable(false);
        txtPrecoUnitario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrecoUnitario.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecoUnitario.setToolTipText("Código de barras ou Nome do produto");
        txtPrecoUnitario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preço Unitário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtParametroBusca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtParametroBusca.setForeground(new java.awt.Color(51, 51, 51));
        txtParametroBusca.setToolTipText("Código de barras ou Nome do produto");
        txtParametroBusca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código/Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        txtParametroBusca.setMinimumSize(new java.awt.Dimension(11, 38));
        txtParametroBusca.setPreferredSize(new java.awt.Dimension(11, 38));
        txtParametroBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarProduto(evt);
            }
        });

        buttonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(50, 138, 138));
        buttonCancelar.setText("CANCELAR");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarVenda(evt);
            }
        });

        buttonFinalizarVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonFinalizarVenda.setForeground(new java.awt.Color(50, 138, 138));
        buttonFinalizarVenda.setText("FINALIZAR");
        buttonFinalizarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFinalizarVendabuttonPagamento(evt);
            }
        });
        buttonFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarVendaActionPerformed(evt);
            }
        });

        buttonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAdicionar.setForeground(new java.awt.Color(50, 138, 138));
        buttonAdicionar.setText("ADICIONAR");
        buttonAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAdicionarItem(evt);
            }
        });
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        jSpinnerQuantidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jSpinnerQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        javax.swing.GroupLayout panelAddItemVendaLayout = new javax.swing.GroupLayout(panelAddItemVenda);
        panelAddItemVenda.setLayout(panelAddItemVendaLayout);
        panelAddItemVendaLayout.setHorizontalGroup(
            panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddItemVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddItemVendaLayout.createSequentialGroup()
                        .addComponent(txtParametroBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddItemVendaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelAddItemVendaLayout.createSequentialGroup()
                                    .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinnerQuantidade)))
                            .addGroup(panelAddItemVendaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(buttonAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFinalizarVenda)))
                        .addGap(207, 207, 207))))
        );
        panelAddItemVendaLayout.setVerticalGroup(
            panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddItemVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtParametroBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecoUnitario)
                    .addComponent(txtCodigoBarra)
                    .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(panelAddItemVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGeralVenda.add(panelAddItemVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 470, 500));

        tbItensVenda.setBackground(new java.awt.Color(204, 204, 204));
        tbItensVenda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Qtd", "Preço", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItensVenda.setGridColor(new java.awt.Color(204, 204, 204));
        tbItensVenda.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tbItensVenda.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbItensVenda);
        if (tbItensVenda.getColumnModel().getColumnCount() > 0) {
            tbItensVenda.getColumnModel().getColumn(0).setMinWidth(60);
            tbItensVenda.getColumnModel().getColumn(0).setMaxWidth(90);
            tbItensVenda.getColumnModel().getColumn(1).setMinWidth(150);
            tbItensVenda.getColumnModel().getColumn(1).setMaxWidth(300);
            tbItensVenda.getColumnModel().getColumn(2).setMinWidth(45);
            tbItensVenda.getColumnModel().getColumn(2).setMaxWidth(80);
            tbItensVenda.getColumnModel().getColumn(3).setMinWidth(90);
            tbItensVenda.getColumnModel().getColumn(3).setMaxWidth(120);
            tbItensVenda.getColumnModel().getColumn(4).setMinWidth(90);
            tbItensVenda.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        panelGeralVenda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 600, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeralVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeralVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarVenda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarVenda
        // TODO add your handling code here:
        new Utilitarios().limpaTela(panelGeralVenda);
        DefaultTableModel dados = (DefaultTableModel) tbItensVenda.getModel();
        dados.setRowCount(0);
        txtTotalVenda.setText("0,00");
        new Utilitarios().limpaTela(panelAddItemVenda);
    }//GEN-LAST:event_buttonCancelarVenda

    private void buttonFinalizarVendabuttonPagamento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFinalizarVendabuttonPagamento
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFinalizarVendabuttonPagamento

    private void buttonFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarVendaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel carrinho = (DefaultTableModel) tbItensVenda.getModel();
        String totalVendaFormatado = txtTotalVenda.getText().replace(".", "").replace(",", ".");
        
        Sales sale = new Sales(totalVendaDouble(totalVendaFormatado), dataAtual(), dataAtual());
        
        SalesDAO dao = new SalesDAO();
        dao.abrirT().incluir(sale).fecharT().fechar();

        for (int i = 0; i < carrinho.getRowCount(); i++) {
            carrinho.getValueAt(i, 0);
            carrinho.getValueAt(i, 1);
            carrinho.getValueAt(i, 2);
            carrinho.getValueAt(i, 3);
            carrinho.getValueAt(i, 4);
        }
//        JOptionPane.showMessageDialog(null, sale.getId());
        FormPagamento pagamento = new FormPagamento();
        pagamento.txtTotalVendaPagamento.setText(String.valueOf(txtTotalVenda.getText()));
        pagamento.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buttonFinalizarVendaActionPerformed

    private void buscarProduto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProduto
        // TODO add your handling code here:
        buscarProduto();

    }//GEN-LAST:event_buscarProduto

    private void buttonAdicionarItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAdicionarItem
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarItem

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
        montaTabela();
        new Utilitarios().limpaTela(panelAddItemVenda);
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendas().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonFinalizarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantidade;
    private javax.swing.JPanel panelAddItemVenda;
    private javax.swing.JPanel panelGeralVenda;
    private javax.swing.JTable tbItensVenda;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtParametroBusca;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtTotalVenda;
    // End of variables declaration//GEN-END:variables
}
